// <auto-generated />
using System;
using MAVN.Service.OperationsHistory.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Service.OperationsHistory.MsSqlRepositories.Migrations
{
    [DbContext(typeof(OperationsHistoryContext))]
    partial class OperationsHistoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operation_history")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.BonusCashInEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnName("transaction_id")
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset")
                        .HasColumnType("text");

                    b.Property<string>("BonusType")
                        .IsRequired()
                        .HasColumnName("bonus_type")
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnName("campaign_id")
                        .HasColumnType("text");

                    b.Property<string>("ConditionId")
                        .HasColumnName("condition_id")
                        .HasColumnType("text");

                    b.Property<string>("ConditionName")
                        .HasColumnName("condition_name")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<string>("ExternalOperationId")
                        .HasColumnName("external_operation_id")
                        .HasColumnType("text");

                    b.Property<string>("LocationCode")
                        .HasColumnName("location_code")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .HasColumnName("location_id")
                        .HasColumnType("text");

                    b.Property<string>("PartnerId")
                        .HasColumnName("partner_id")
                        .HasColumnType("text");

                    b.Property<string>("ReferralId")
                        .HasColumnName("referral_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TransactionId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("bonus_cash_in");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.BurnRuleEntity", b =>
                {
                    b.Property<string>("BurnRuleId")
                        .HasColumnName("burn_rule_id")
                        .HasColumnType("text");

                    b.Property<string>("BurnRuleName")
                        .IsRequired()
                        .HasColumnName("burn_rule_name")
                        .HasColumnType("text");

                    b.HasKey("BurnRuleId");

                    b.ToTable("burn_rules");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.CampaignEntity", b =>
                {
                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CampaignId");

                    b.ToTable("campaigns");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.CustomerTierEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("TierId")
                        .IsRequired()
                        .HasColumnName("tier_id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("tiers_updates");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.FeeCollectedOperationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset_symbol")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<string>("Fee")
                        .IsRequired()
                        .HasColumnName("fee")
                        .HasColumnType("text");

                    b.Property<int>("Reason")
                        .HasColumnName("reason")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("fee_collected_operations");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.LinkWalletOperationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnName("direction")
                        .HasColumnType("text");

                    b.Property<string>("Fee")
                        .IsRequired()
                        .HasColumnName("fee")
                        .HasColumnType("text");

                    b.Property<string>("PrivateAddress")
                        .IsRequired()
                        .HasColumnName("private_address")
                        .HasColumnType("text");

                    b.Property<string>("PublicAddress")
                        .HasColumnName("public_address")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("link_wallet_operations");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.LinkedWalletTransferEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnName("direction")
                        .HasColumnType("integer");

                    b.Property<string>("PrivateAddress")
                        .IsRequired()
                        .HasColumnName("private_address")
                        .HasColumnType("text");

                    b.Property<string>("PublicAddress")
                        .IsRequired()
                        .HasColumnName("public_address")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("linked_wallet_transfer");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.PartnersPaymentEntity", b =>
                {
                    b.Property<string>("PaymentRequestId")
                        .HasColumnName("payment_request_id")
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset_symbol")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .HasColumnName("location_id")
                        .HasColumnType("text");

                    b.Property<string>("PartnerId")
                        .IsRequired()
                        .HasColumnName("partner_id")
                        .HasColumnType("text");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnName("partner_name")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PaymentRequestId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("partners_payments");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.PartnersPaymentRefundEntity", b =>
                {
                    b.Property<string>("PaymentRequestId")
                        .HasColumnName("payment_request_id")
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset_symbol")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .HasColumnName("location_id")
                        .HasColumnType("text");

                    b.Property<string>("PartnerId")
                        .IsRequired()
                        .HasColumnName("partner_id")
                        .HasColumnType("text");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnName("partner_name")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PaymentRequestId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("refunded_partners_payments");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.ReferralStakeEntity", b =>
                {
                    b.Property<string>("ReferralId")
                        .HasColumnName("referral_id")
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset")
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnName("campaign_id")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ReferralId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("referral_stakes");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.ReleasedReferralStakeEntity", b =>
                {
                    b.Property<string>("ReferralId")
                        .HasColumnName("referral_id")
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset")
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnName("campaign_id")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ReferralId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("released_referral_stakes");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.SmartVoucherPaymentEntity", b =>
                {
                    b.Property<string>("PaymentRequestId")
                        .HasColumnName("payment_request_id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("numeric");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset_symbol")
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnName("campaign_id")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartnerId")
                        .HasColumnName("partner_id")
                        .HasColumnType("uuid");

                    b.Property<string>("PartnerName")
                        .HasColumnName("partner_name")
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnName("short_code")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Vertical")
                        .HasColumnName("vertical")
                        .HasColumnType("text");

                    b.HasKey("PaymentRequestId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("smart_voucher_payments");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.SmartVoucherTransferEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("numeric");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset_symbol")
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnName("campaign_id")
                        .HasColumnType("text");

                    b.Property<Guid>("NewCustomerId")
                        .HasColumnName("new_customer_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OldCustomerId")
                        .HasColumnName("old_customer_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartnerId")
                        .HasColumnName("partner_id")
                        .HasColumnType("uuid");

                    b.Property<string>("PartnerName")
                        .HasColumnName("partner_name")
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnName("short_code")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Vertical")
                        .HasColumnName("vertical")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("NewCustomerId");

                    b.HasIndex("OldCustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("smart_voucher_transfers");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.SmartVoucherUseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("numeric");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset_symbol")
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnName("campaign_id")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedCustomerId")
                        .HasColumnName("linked_customer_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnName("location_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartnerId")
                        .HasColumnName("partner_id")
                        .HasColumnType("uuid");

                    b.Property<string>("PartnerName")
                        .HasColumnName("partner_name")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Vertical")
                        .HasColumnName("vertical")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("smart_voucher_uses");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.TransactionHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnName("customer_id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnName("transaction_id")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TransactionId");

                    b.ToTable("transaction_history");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.TransferEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnName("transaction_id")
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset")
                        .HasColumnType("text");

                    b.Property<string>("ExternalOperationId")
                        .HasColumnName("external_operation_id")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverCustomerId")
                        .IsRequired()
                        .HasColumnName("receiver_id")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverWalletAddress")
                        .IsRequired()
                        .HasColumnName("receiver_wallet_address")
                        .HasColumnType("text");

                    b.Property<string>("SenderCustomerId")
                        .IsRequired()
                        .HasColumnName("sender_id")
                        .HasColumnType("text");

                    b.Property<string>("SenderWalletAddress")
                        .IsRequired()
                        .HasColumnName("sender_wallet_address")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TransactionId");

                    b.HasIndex("ReceiverCustomerId");

                    b.HasIndex("SenderCustomerId");

                    b.ToTable("transfer");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.VoucherPurchasePaymentEntity", b =>
                {
                    b.Property<Guid>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("transfer_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnName("amount")
                        .HasColumnType("text");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnName("asset_symbol")
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpendRuleId")
                        .HasColumnName("spend_rule_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("VoucherId")
                        .HasColumnName("voucher_id")
                        .HasColumnType("uuid");

                    b.HasKey("TransferId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Timestamp");

                    b.ToTable("voucher_purchase_payments");
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.BonusCashInEntity", b =>
                {
                    b.HasOne("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.CampaignEntity", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.ReferralStakeEntity", b =>
                {
                    b.HasOne("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.CampaignEntity", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.ReleasedReferralStakeEntity", b =>
                {
                    b.HasOne("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.CampaignEntity", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.SmartVoucherPaymentEntity", b =>
                {
                    b.HasOne("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.CampaignEntity", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.SmartVoucherTransferEntity", b =>
                {
                    b.HasOne("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.CampaignEntity", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.SmartVoucherUseEntity", b =>
                {
                    b.HasOne("MAVN.Service.OperationsHistory.MsSqlRepositories.Entities.CampaignEntity", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
